### ISSUE TITLE
Enhance XLSX templates with examples for expected properties

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/data-manager-app#675]
**Is your feature request related to a problem? Please describe.**
Some properties in e.g. the NGS measurement template are not very straight forward to understand, what the required values look like.

**Describe the solution you'd like**
An additional column with examples in the template. Also, for the ontology CURI it would be very helpful to link the ontology lookup service.

**Comment by sven1103** [comment]
Issue was reported by @d4straub

**Comment by sven1103** [comment]
@Shraddha0903: Only problem i see with this request: the Ontology Lookup cannot be referenced, since it is only available from within the project context.

**Comment by Shraddha0903** [comment]
Explored 2 potential solutions for displaying a brief description and example of the metadata properties in the sheet:
1. As a comment (appears when you hover over the cell)
2. As Input message of the Data validation option (appears when you click on the cell)

After having a discussion with @KochTobi and @Steffengreiner  we decided to go with the second option.

The first option was a good option to display long text with formatting, however the disadvantage was that the comments can be edited, deleted or replied to by anyone who downloads the sheet and they cannot be locked.

The second option of having a prompt message when one clicks on the cell is the next best option as it can display the message without the user being able to modify/delete easily. However, the font size of the text message is very small and the input message also has a character limit to it. But since we are short on options, the option of using Data validation input message for displaying metadata property description and example can be used by showing shorter descriptions.

I have attached a file containing the list of short descriptions for the Proteomics metadata sheet. Please refer to that.

[MetadataProperties_Proteomics.txt](https://github.com/user-attachments/files/16932330/MetadataProperties_Proteomics.txt)

**Comment by KochTobi** [comment]
Hi @d4straub 
We are looking into ways to provide you with example values making the spreadsheet filling easier. What do you think of the help boxes shown in the spreadsheets?
[ngs_measurement_registration_sheet.xlsx](https://github.com/user-attachments/files/17504848/ngs_measurement_registration_sheet.xlsx)
[proteomics_measurement_registration_sheet.xlsx](https://github.com/user-attachments/files/17504849/proteomics_measurement_registration_sheet.xlsx)
[QVAMP_ngs_measurements.xlsx](https://github.com/user-attachments/files/17504850/QVAMP_ngs_measurements.xlsx)
[QVAMP_proteomics_measurements.xlsx](https://github.com/user-attachments/files/17504851/QVAMP_proteomics_measurements.xlsx)

**Comment by d4straub** [comment]
Hi @KochTobi , yes, that helps a lot I think! (this is also how its done in SRA templates)

**Comment by Shraddha0903** [comment]
@KochTobi List of descriptions for the sample registration excel template

[MetadataProperties_SampleRegistration.txt](https://github.com/user-attachments/files/17555994/MetadataProperties_SampleRegistration.txt)
