### ISSUE TITLE
`timsTOF fleX MALDI-2` not found in ontology search

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#734]
**Is your feature request related to a problem? Please describe.**
It was noted that the instrument `timsTOF fleX MALDI-2` was not found in our ontology search.
https://ontobee.org/ontology/MS?iri=http://purl.obolibrary.org/obo/MS_1003397

**Describe the solution you'd like**
The instrument to be included in our ontology search.

**Describe alternatives you've considered**
Using the more general type described in the ontology.

**Comment by sven1103** [comment]
I looked into it, and this issue is a symptom of a much bigger problem:

The PSI-MS ontology format broke, such that the library we use ([owlready2](https://owlready2.readthedocs.io/en/latest/)) is not able to parse the content anymore.

Of course we can escalate the discussion to the maintainers, but what I have seen so far with OWL parser support and robust OWL processing, plus the maintenance effort we are having, I am concerned.

In addition, I think we do redundant effort, since there seems now solutions available that we can make use of:
https://terminology.tib.eu/ts/

Thus I will open an own issue for this and reference it here.

**Comment by sven1103** [comment]
will be solved in #785
