### ISSUE TITLE
Define the term `Organism Id`

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#735]
**Is your feature request related to a problem? Please describe.**
For some users it is unclear what is meant by `organism id` in the sample batch registration step.

**Describe the solution you'd like**
Remove the organism id or rename it.

**Describe alternatives you've considered**
Add a definition and intended use of the organism id to the documentation and teach users about it.

**Additional Context**
For some users it was clear what was meant by organism id and they used it to differentiate between orignin individuals of their samples.

**Comment by Shraddha0903** [comment]
Some name suggestions :
Biological Replicate (FBS)
Organism Biological Replicate (FBS)
Biological replicate organism (SP)
Organism source (SP)

We need to finalise a term and also provide a definition and example for it in the sample registration metadata template.

**Comment by sven1103** [comment]
Dear @FraBarSol and @oquendoM, 

we decided to escalate this issue again and not work on it.

I fear, that the fact that there are so many uncertainties about this property, is probably because we dont understand what it solves in the first place.

So if you can explain again to us, that it is needed for, we might come up with a better term for it.

**Comment by sven1103** [comment]
Discussing it together with @FraBarSol and @oquendoM and @Shraddha0903 , 

we decided now (for the next at least 5 years :D) to accept, that organism ID is a term nobody understands, so we vote for explicit "**Biological Replicate**".
