### ISSUE TITLE
I want to link my affiliation to my profile

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/data-manager-app#742]
**Is your feature request related to a problem? Please describe.**
As a scientist I have an interest in having my affiliation linked to my profile. This could be super helpful in auto-filling my measurement registration sheets (as it is always the same for the place I work at).
It would be great to add the affiliation to my profile.

**Describe the solution you'd like**
Having a list of affiliations with organisation I am affiliated with in my profile. Use this list when suggesting possible entries for the measurement sheet I upload to register a measurement.

**Describe alternatives you've considered**
Allow me to store favorite ROR ids somewhere.

**Additional context**

**Comment by sven1103** [comment]
ORCID actually fetches the ROR ID automatically, when a user enters employment information. You can check out my ORCID public record:
https://orcid.org/0000-0001-8835-2219

I never entered the ROR ID manually :)

We can use this information to fetch existing affiliations:
https://info.orcid.org/documentation/api-tutorials/api-tutorial-read-data-on-a-record/

The remaining question is: should we allow users to provide the affiliation by themselves?

I am tending towards negating this, since there should be only one place of truth. Moreover, since the ORCID upon publication and the ROR ID is adhering to the FAIR principles (persistent, globally unique identifier), I am currently convinced that users have to use their public research record for the provenance tracking. We must not offer a secretly second way of providing provenance information.

**Comment by sven1103** [comment]
Pre-condition: 

- The user has an connected ORCID account
- The user has entered at least one public employment entry with a ROR ID connected to their ORCID record

Use Case:
- The user navigate to their profile
- The user can see their available affiliation with ROR ID entry in the user profile page
